### ISSUE TITLE
Problème d'installation de networkx

### ISSUE THREAD

**Issue by SarahMinich** [pagination-problem/2-tile#1]
Je n'arrive pas à faire fonctionner networkx pour le moment (cf  commit 24dad59). J'ai essayé cette [méthode ](https://stackoverflow.com/questions/50629513/errors-importing-networkx-package). Les désinstallations et l'installation se passent bien mais j'ai toujours cette erreur : 
```
Exception has occurred: ModuleNotFoundError
No module named 'networkx'
```

Je me renseigne sur les absolute / relative imports ([ici](https://realpython.com/absolute-vs-relative-python-imports/) par exemple) et je vais peut-être essayer de mettre à jour ma PYTHONPATH, je ne sais pas.

**Comment by laowantong** [comment]
Désolé, je suis incompétent sur Windows. Je t'ai conseillé de te faire acheter un mac pour avoir un système Unix et un matériel de qualité. Tu peux également essayer Linux, mais je pense que MacOS est plus facile à prendre en main.

**Comment by SarahMinich** [comment]
Je doute que juste pour des facilités d'installation, je puisse demander un mac !
Maintenant j'ai pu installer la bibliothèque networkx mais j'ai un autre souci et ça je ne le comprends pas du tout.
